version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:15.4
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "${POSTGRES_PORT}:3000"
    networks:
      default:
        ipv4_address: $POSTGRES_IP
  nginx:
    container_name: nginx
    image: nginx:1.17.8@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03
    depends_on: [ db ]
    volumes:
      - ${PWD}/nginx:/etc/nginx
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "${NGINX_PORT}:80"
    networks:
      default:
        ipv4_address: $NGINX_IP
networks:
  default:
    name: nova_main_network
    ipam:
      driver: default
      config:
        - subnet: "$NETWORK_IP/16"
