version: "3.7"

services:
  manager:
    container_name: nova_manager
    build: ./manager
    restart: on-failure
    stop_grace_period: 5m30s
    volumes:
      - ${PWD}:${PWD}
      - ${PWD}/events/signals:/signals
      - ${PWD}/statuses:/statuses
      - ${PWD}/db:/db
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BINARY:-/usr/bin/docker}:/usr/bin/docker
    environment:
      PORT: $MANAGER_PORT
      SHUTDOWN_SIGNAL_FILE: "/signals/shutdown"
      REBOOT_SIGNAL_FILE: "/signals/reboot"
      METADATA_FILE: "/db/info.json"
      STATUS_DIR: "/statuses"
    networks:
      default:
        ipv4_address: $MANAGER_IP
  nginx:
    container_name: nginx
    image: nginx:1.17.8@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03
    depends_on: [manager]
    volumes:
      - ${PWD}/nginx:/etc/nginx
      - ${PWD}/front/dist:/var/www/html
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "${NGINX_PORT}:80"
    networks:
      default:
        ipv4_address: $NGINX_IP
networks:
  default:
    name: nova_main_network
    ipam:
      driver: default
      config:
        - subnet: "$NETWORK_IP/16"
